# Generated by Django 3.0.5 on 2020-04-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='name',
            field=models.CharField(default='hej', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='parti',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.party'),
            preserve_default=False,
        ),
    ]
