# Generated by Django 3.0.5 on 2020-04-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200419_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parti',
        ),
        migrations.AddField(
            model_name='message',
            name='party',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.Party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(to='app.Party'),
        ),
    ]
