# Generated by Django 3.0.5 on 2020-04-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200419_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='game',
            field=models.CharField(default='Skyrim', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='platform',
            field=models.CharField(default='Playstation 4', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.Party'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(to='app.Party'),
        ),
    ]
