# Generated by Django 3.0.6 on 2020-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200423_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.CharField(default='no description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.Party'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(to='app.Party'),
        ),
    ]
