# Generated by Django 3.0.6 on 2020-05-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200517_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.Party'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(related_name='users', to='app.Party'),
        ),
    ]
